### ISSUE TITLE
Unable to paste text longer than 11 characters

### ISSUE THREAD

**Issue by nanangarsyad** [akavel/up#37] opened 2018-11-02 14:12 UTC
I tried to do some pipelining for comparison.
But when I tried to paste the content of my clipboard to  this tools command prompt, only the first 11 characters got copied to it.

Here's the screencast in case needed.
![plumber-up](https://user-images.githubusercontent.com/7588442/47920146-ed997600-dee3-11e8-9e87-c679cd88365c.gif)

**Comment by akavel** [comment] 2018-11-02 16:07
Thanks a lot for the report, and for the screencast! (By the way, can I ask what did you use to make it? :) )

I think I noticed something similar once already, so it should hopefully be possible for me to reproduce it. That's the good news...

The bad news is, that I currently have no *slightest* idea what could be the reason of this :(

***EDIT:*** Hmmmm; buuuut.... from what I see, you seem to be using ~v0.1 of up; could you please retry, but using [**the newest version**](https://github.com/akavel/up/releases)? I think there's *some* chance that the "Press Enter to run" change I did in 0.2 *might* have a side effect of fixing this issue. Please let me know if you can do this, and if it fixed this for you — or not! And please note, that with 0.2+ you'll now have to **press Enter to run the commands** (they aren't executed "immediately" as in the initial 0.1 version anymore).

TIA!

**Comment by nanangarsyad** [comment] 2018-11-02 22:06
Hi akavel.  Thanks for the replay.
I've just tried version 0.3.1 as your suggestion, but sadly to say, the issues still there.

As for the tools I'd been using were [peek](https://github.com/phw/peek) (for screen recording) and [screenkey](https://github.com/wavexx/screenkey) (for keypress screen cast)

**Comment by mackushev** [comment] 2018-11-03 07:38
I have the same issue on Ubuntu 18.04.1

**Comment by sarathsp06** [comment] 2018-12-04 04:00
Is it fixed ?

**Comment by akavel** [comment] 2018-12-04 08:50
@sarathsp06 Nope, still open.

**Comment by thoaionline** [comment] 2018-12-07 14:37
Apologies, I got started but then dropped this when I wiped my PC (last month). Quite occupied these days after starting a new job so this is now up for grab by a good hand.

**Comment by thoaionline** [comment] 2018-12-07 14:42
Here's something that may help whoever picking this up. I suspect this was due to the app unable to pick up text typed in too quickly. On my MacOS, `up` will work just fine if you paste slowly (Edit \ Paste Special \ Paste Slowly), or use the `Paste Special` option and `reduce the chunk size` (to anything less than 11 bytes)

**Comment by kdabir** [comment] 2019-07-31 02:43
Thanks for the tip @thoaionline. For me `Paste Slower` didn't work but `Advanced Paste` with reduced chunk size work. 

Just for posterity, here is what worked for me :
![image](https://user-images.githubusercontent.com/735240/62179602-bcfb4580-b36a-11e9-9bab-bdedab1b6e7c.png)

**Comment by akavel** [comment] 2020-10-29 21:03
I guess it may be due to https://github.com/gdamore/tcell/issues/200. As such I suppose it may get fixed if I upgrade tcell to 1.1.3+ (which should have https://github.com/gdamore/tcell/commit/12658f0d5770aa5468290658b203aac1be62b647).

**Comment by akavel** [comment] 2020-10-29 21:48
Would you mind checking out whether this is now fixed with **[up v0.4](https://github.com/akavel/up/releases/tag/v0.4)**, or is it still broken?

**Comment by akavel** [comment] 2020-12-14 18:35
I tested in Konsole on Linux, seems to work now. In case of problems, please comment here or open new issue.

**Closed by akavel** 2020-12-14 18:35 UTC
Labels: deficiency, 🤕 help wanted
